export enum NOTIFICATION_TYPES {
    NOTIFY = 'NOTIFY',
    PING = 'Ping',
    FORBIDDEN = 'FORBIDDEN',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    SUCCESS = 'SUCCESS',
    REFRESH = 'REFRESH',
    SERVICE_UPDATE = 'SERVICE_UPDATE'
}