version: '3'


volumes:
  esdata1:
    driver: local
   
networks:
  devnetwork:
    driver: bridge

services:
 rabbitmq:
  build: 
    context: ./docker/rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  networks:
    - devnetwork     
  volumes:
    - /opt/rabbitmq:/var/lib/rabbitmq
 chatterbot-engine:
  build:
    context: ./docker/chatterbot-engine
  environment:
    - RABBITMQ_USER=admin
    - RABBITMQ_PASSWORD=rabbitmqadmin
    - RABBITMQ_SERVER=rabbitmq
    - RABBITMQ_PORT=5672
    - RABBITMQ_EXCHANGE=bot_response_exchange
    - RABBITMQ_VIRTUALHOST=/
    - RABBITMQ_BOT_INCOMING_QUEUE=bot_request_queue
    - MONGODB_SERVER=db-mongo
    - MONGODB_USER=devroot
    - MONGODB_PASSWORD=devroot
    - MONGODB_PORT=27017
    - NOTIFY_EXCHANGE=notification_exchange
    - ENV CHAT_BASE_API_KEY=d57b42e4-d3b9-468d-b698-dbc1c106e76b
  networks:
    - devnetwork  
 ingestion-service:
  build:
    context: ./docker/ingestion-service
  environment:
    - RABBITMQ_USER=admin
    - RABBITMQ_PASSWORD=rabbitmqadmin
    - RABBITMQ_SERVER=rabbitmq
    - RABBITMQ_PORT=5672
    - RABBITMQ_EXCHANGE=bot_request_exchange
    - RABBITMQ_VIRTUALHOST=/
    - RABBITMQ_BOT_INCOMING_QUEUE=ingestion_queue
    - MONGODB_SERVER=db-mongo
    - MONGODB_USER=devroot
    - MONGODB_PASSWORD=devroot
    - MONGODB_PORT=27017
  networks:
    - devnetwork
 gmailkbclient:
  build:
    context: ./docker/gmailkbclient
  environment:
    - GMAIL_USER=lord.lewin.test@gmail.com
    - GMAIL_PASSWORD=Atos@1234
    - RABBITMQ_USER=admin
    - RABBITMQ_PASSWORD=rabbitmqadmin
    - RABBITMQ_SERVER=rabbitmq
    - RABBITMQ_PORT=5672
    - RABBITMQ_EXCHANGE=ingestion_exchange
    - RABBITMQ_VIRTUALHOST=/
    - RABBITMQ_BOT_INCOMING_QUEUE=ingestion_queue
  networks:
    - devnetwork    
 notification-service:
  build:
    context: ./docker/notification-service
  environment:
    - GMAIL_USER=lord.lewin.test@gmail.com
    - GMAIL_PASSWORD=Atos@1234
    - RABBITMQ_USER=admin
    - RABBITMQ_PASSWORD=rabbitmqadmin
    - RABBITMQ_SERVER=rabbitmq
    - RABBITMQ_PORT=5672
    - RABBITMQ_EXCHANGE=notification_exchange
    - RABBITMQ_VIRTUALHOST=/
    - RABBITMQ_BOT_INCOMING_QUEUE=notification_queue
  networks:
    - devnetwork    
 db-mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
    - "28017:27017"
  networks:
    - devnetwork
  environment:
    - MONGO_INITDB_ROOT_USERNAME=devroot
    - MONGO_INITDB_ROOT_PASSWORD=devroot
    - MONGO_INITDB_DATABASE=project        
 db-mongo-admin:
  image: mongo-express
  ports:
    - "8081:8081"
  networks:
    - devnetwork
  environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    - ME_CONFIG_MONGODB_SERVER=db-mongo
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
    - ME_CONFIG_MONGODB_ADMINUSERNAME=devroot
    - ME_CONFIG_MONGODB_ADMINPASSWORD=devroot
  links:
    - db-mongo
 portal:
  build:
    context: ./docker/portal
  environment:
    - RABBITMQ_USER=admin
    - RABBITMQ_PASSWORD=rabbitmqadmin
    - RABBITMQ_SERVER=rabbitmq
    - RABBITMQ_PORT=5672
    - ENVIRONMENT=prod
  networks:
    - devnetwork  

      
 