set KEEP_WSS_CONNECTION_ALIVE=100000
set ENVIRONMENT=development
set RABBITMQ_USER=admin
set RABBITMQ_PASSWORD=rabbitmqadmin
set RABBITMQ_SERVER=192.168.99.100
set RABBITMQ_PORT=5672
set RABBITMQ_VIRTUALHOST=/
